// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/attachment_service.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/attachment_service.proto.
 */
export const file_api_v1_attachment_service: GenFile = /*@__PURE__*/
  fileDesc("Ch9hcGkvdjEvYXR0YWNobWVudF9zZXJ2aWNlLnByb3RvEgZhcGkudjEimwEKCkF0dGFjaG1lbnQSDAoEbmFtZRgBIAEoCRIvCgtjcmVhdGVfdGltZRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEAoIZmlsZW5hbWUYAyABKAkSDwoHY29udGVudBgEIAEoDBIMCgR0eXBlGAUgASgJEgwKBHNpemUYBiABKAMSDwoHbm90ZV9pZBgHIAEoCSJYChdDcmVhdGVBdHRhY2htZW50UmVxdWVzdBImCgphdHRhY2htZW50GAEgASgLMhIuYXBpLnYxLkF0dGFjaG1lbnQSFQoNYXR0YWNobWVudF9pZBgCIAEoCSJQChZMaXN0QXR0YWNobWVudHNSZXF1ZXN0EhEKCXBhZ2Vfc2l6ZRgBIAEoBRISCgpwYWdlX3Rva2VuGAIgASgJEg8KB25vdGVfaWQYAyABKAkibwoXTGlzdEF0dGFjaG1lbnRzUmVzcG9uc2USJwoLYXR0YWNobWVudHMYASADKAsyEi5hcGkudjEuQXR0YWNobWVudBIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkSEgoKdG90YWxfc2l6ZRgDIAEoBSIkChRHZXRBdHRhY2htZW50UmVxdWVzdBIMCgRuYW1lGAEgASgJIicKF0RlbGV0ZUF0dGFjaG1lbnRSZXF1ZXN0EgwKBG5hbWUYASABKAkicgoXVXBkYXRlQXR0YWNobWVudFJlcXVlc3QSJgoKYXR0YWNobWVudBgBIAEoCzISLmFwaS52MS5BdHRhY2htZW50Ei8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzazKJAwoRQXR0YWNobWVudFNlcnZpY2USRwoQQ3JlYXRlQXR0YWNobWVudBIfLmFwaS52MS5DcmVhdGVBdHRhY2htZW50UmVxdWVzdBoSLmFwaS52MS5BdHRhY2htZW50ElIKD0xpc3RBdHRhY2htZW50cxIeLmFwaS52MS5MaXN0QXR0YWNobWVudHNSZXF1ZXN0Gh8uYXBpLnYxLkxpc3RBdHRhY2htZW50c1Jlc3BvbnNlEkEKDUdldEF0dGFjaG1lbnQSHC5hcGkudjEuR2V0QXR0YWNobWVudFJlcXVlc3QaEi5hcGkudjEuQXR0YWNobWVudBJLChBEZWxldGVBdHRhY2htZW50Eh8uYXBpLnYxLkRlbGV0ZUF0dGFjaG1lbnRSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EkcKEFVwZGF0ZUF0dGFjaG1lbnQSHy5hcGkudjEuVXBkYXRlQXR0YWNobWVudFJlcXVlc3QaEi5hcGkudjEuQXR0YWNobWVudEKVAQoKY29tLmFwaS52MUIWQXR0YWNobWVudFNlcnZpY2VQcm90b1ABWjZnaXRodWIuY29tL3dkbXN5aGgvc2ltcGxlLW5vdGVzL3Byb3RvL2dlbi9hcGkvdjE7YXBpdjGiAgNBWFiqAgZBcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFcR1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM", [file_google_protobuf_empty, file_google_protobuf_field_mask, file_google_protobuf_timestamp]);

/**
 * Attachment 附件消息
 *
 * @generated from message api.v1.Attachment
 */
export type Attachment = Message<"api.v1.Attachment"> & {
  /**
   * 附件名称，格式：attachments/{attachment}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * 创建时间戳
   *
   * @generated from field: google.protobuf.Timestamp create_time = 2;
   */
  createTime?: Timestamp;

  /**
   * 文件名
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * 仅输入。附件内容
   *
   * @generated from field: bytes content = 4;
   */
  content: Uint8Array;

  /**
   * MIME类型
   *
   * @generated from field: string type = 5;
   */
  type: string;

  /**
   * 仅输出。附件大小（字节）
   *
   * @generated from field: int64 size = 6;
   */
  size: bigint;

  /**
   * 可选。关联的笔记，格式：notes/{note}
   *
   * @generated from field: string note_id = 7;
   */
  noteId: string;
};

/**
 * Describes the message api.v1.Attachment.
 * Use `create(AttachmentSchema)` to create a new message.
 */
export const AttachmentSchema: GenMessage<Attachment> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 0);

/**
 * CreateAttachmentRequest 创建附件请求
 *
 * @generated from message api.v1.CreateAttachmentRequest
 */
export type CreateAttachmentRequest = Message<"api.v1.CreateAttachmentRequest"> & {
  /**
   * 必需。要创建的附件
   *
   * @generated from field: api.v1.Attachment attachment = 1;
   */
  attachment?: Attachment;

  /**
   * 可选。要使用的附件ID
   *
   * @generated from field: string attachment_id = 2;
   */
  attachmentId: string;
};

/**
 * Describes the message api.v1.CreateAttachmentRequest.
 * Use `create(CreateAttachmentRequestSchema)` to create a new message.
 */
export const CreateAttachmentRequestSchema: GenMessage<CreateAttachmentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 1);

/**
 * ListAttachmentsRequest 列出附件请求
 *
 * @generated from message api.v1.ListAttachmentsRequest
 */
export type ListAttachmentsRequest = Message<"api.v1.ListAttachmentsRequest"> & {
  /**
   * 可选。返回的最大附件数量
   *
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * 可选。分页令牌
   *
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * 可选。按note_id过滤
   *
   * @generated from field: string note_id = 3;
   */
  noteId: string;
};

/**
 * Describes the message api.v1.ListAttachmentsRequest.
 * Use `create(ListAttachmentsRequestSchema)` to create a new message.
 */
export const ListAttachmentsRequestSchema: GenMessage<ListAttachmentsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 2);

/**
 * ListAttachmentsResponse 列出附件响应
 *
 * @generated from message api.v1.ListAttachmentsResponse
 */
export type ListAttachmentsResponse = Message<"api.v1.ListAttachmentsResponse"> & {
  /**
   * 附件列表
   *
   * @generated from field: repeated api.v1.Attachment attachments = 1;
   */
  attachments: Attachment[];

  /**
   * 下一页的令牌
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * 附件总数
   *
   * @generated from field: int32 total_size = 3;
   */
  totalSize: number;
};

/**
 * Describes the message api.v1.ListAttachmentsResponse.
 * Use `create(ListAttachmentsResponseSchema)` to create a new message.
 */
export const ListAttachmentsResponseSchema: GenMessage<ListAttachmentsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 3);

/**
 * GetAttachmentRequest 获取附件请求
 *
 * @generated from message api.v1.GetAttachmentRequest
 */
export type GetAttachmentRequest = Message<"api.v1.GetAttachmentRequest"> & {
  /**
   * 必需。附件名称，格式：attachments/{attachment}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.GetAttachmentRequest.
 * Use `create(GetAttachmentRequestSchema)` to create a new message.
 */
export const GetAttachmentRequestSchema: GenMessage<GetAttachmentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 4);

/**
 * DeleteAttachmentRequest 删除附件请求
 *
 * @generated from message api.v1.DeleteAttachmentRequest
 */
export type DeleteAttachmentRequest = Message<"api.v1.DeleteAttachmentRequest"> & {
  /**
   * 必需。附件名称，格式：attachments/{attachment}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.DeleteAttachmentRequest.
 * Use `create(DeleteAttachmentRequestSchema)` to create a new message.
 */
export const DeleteAttachmentRequestSchema: GenMessage<DeleteAttachmentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 5);

/**
 * UpdateAttachmentRequest 更新附件请求
 *
 * @generated from message api.v1.UpdateAttachmentRequest
 */
export type UpdateAttachmentRequest = Message<"api.v1.UpdateAttachmentRequest"> & {
  /**
   * 必需。要更新的附件
   *
   * @generated from field: api.v1.Attachment attachment = 1;
   */
  attachment?: Attachment;

  /**
   * 可选。字段掩码，指定要更新的字段
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message api.v1.UpdateAttachmentRequest.
 * Use `create(UpdateAttachmentRequestSchema)` to create a new message.
 */
export const UpdateAttachmentRequestSchema: GenMessage<UpdateAttachmentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_attachment_service, 6);

/**
 * AttachmentService 处理附件相关操作的服务
 *
 * @generated from service api.v1.AttachmentService
 */
export const AttachmentService: GenService<{
  /**
   * CreateAttachment 创建新附件
   *
   * @generated from rpc api.v1.AttachmentService.CreateAttachment
   */
  createAttachment: {
    methodKind: "unary";
    input: typeof CreateAttachmentRequestSchema;
    output: typeof AttachmentSchema;
  },
  /**
   * ListAttachments 列出所有附件
   *
   * @generated from rpc api.v1.AttachmentService.ListAttachments
   */
  listAttachments: {
    methodKind: "unary";
    input: typeof ListAttachmentsRequestSchema;
    output: typeof ListAttachmentsResponseSchema;
  },
  /**
   * GetAttachment 根据名称返回附件
   *
   * @generated from rpc api.v1.AttachmentService.GetAttachment
   */
  getAttachment: {
    methodKind: "unary";
    input: typeof GetAttachmentRequestSchema;
    output: typeof AttachmentSchema;
  },
  /**
   * DeleteAttachment 根据名称删除附件
   *
   * @generated from rpc api.v1.AttachmentService.DeleteAttachment
   */
  deleteAttachment: {
    methodKind: "unary";
    input: typeof DeleteAttachmentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * UpdateAttachment 更新附件（例如，将其链接到笔记）
   *
   * @generated from rpc api.v1.AttachmentService.UpdateAttachment
   */
  updateAttachment: {
    methodKind: "unary";
    input: typeof UpdateAttachmentRequestSchema;
    output: typeof AttachmentSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_attachment_service, 0);

