// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/category_service.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Category, CategorySchema } from "../../store/note_pb";
import { file_store_note } from "../../store/note_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/category_service.proto.
 */
export const file_api_v1_category_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1hcGkvdjEvY2F0ZWdvcnlfc2VydmljZS5wcm90bxIGYXBpLnYxIkIKFUxpc3RDYXRlZ29yaWVzUmVxdWVzdBIWCg5pbmNsdWRlX2hpZGRlbhgBIAEoCBIRCglwYXJlbnRfaWQYAiABKAMiPQoWTGlzdENhdGVnb3JpZXNSZXNwb25zZRIjCgpjYXRlZ29yaWVzGAEgAygLMg8uc3RvcmUuQ2F0ZWdvcnkiIgoSR2V0Q2F0ZWdvcnlSZXF1ZXN0EgwKBG5hbWUYASABKAkiOgoVQ3JlYXRlQ2F0ZWdvcnlSZXF1ZXN0EiEKCGNhdGVnb3J5GAEgASgLMg8uc3RvcmUuQ2F0ZWdvcnkiawoVVXBkYXRlQ2F0ZWdvcnlSZXF1ZXN0EiEKCGNhdGVnb3J5GAEgASgLMg8uc3RvcmUuQ2F0ZWdvcnkSLwoLdXBkYXRlX21hc2sYAiABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIiUKFURlbGV0ZUNhdGVnb3J5UmVxdWVzdBIMCgRuYW1lGAEgASgJIigKGEdldENhdGVnb3J5QnlTbHVnUmVxdWVzdBIMCgRzbHVnGAEgASgJMrMDCg9DYXRlZ29yeVNlcnZpY2USTwoOTGlzdENhdGVnb3JpZXMSHS5hcGkudjEuTGlzdENhdGVnb3JpZXNSZXF1ZXN0Gh4uYXBpLnYxLkxpc3RDYXRlZ29yaWVzUmVzcG9uc2USOgoLR2V0Q2F0ZWdvcnkSGi5hcGkudjEuR2V0Q2F0ZWdvcnlSZXF1ZXN0Gg8uc3RvcmUuQ2F0ZWdvcnkSQAoOQ3JlYXRlQ2F0ZWdvcnkSHS5hcGkudjEuQ3JlYXRlQ2F0ZWdvcnlSZXF1ZXN0Gg8uc3RvcmUuQ2F0ZWdvcnkSQAoOVXBkYXRlQ2F0ZWdvcnkSHS5hcGkudjEuVXBkYXRlQ2F0ZWdvcnlSZXF1ZXN0Gg8uc3RvcmUuQ2F0ZWdvcnkSRwoORGVsZXRlQ2F0ZWdvcnkSHS5hcGkudjEuRGVsZXRlQ2F0ZWdvcnlSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EkYKEUdldENhdGVnb3J5QnlTbHVnEiAuYXBpLnYxLkdldENhdGVnb3J5QnlTbHVnUmVxdWVzdBoPLnN0b3JlLkNhdGVnb3J5QpMBCgpjb20uYXBpLnYxQhRDYXRlZ29yeVNlcnZpY2VQcm90b1ABWjZnaXRodWIuY29tL3dkbXN5aGgvc2ltcGxlLW5vdGVzL3Byb3RvL2dlbi9hcGkvdjE7YXBpdjGiAgNBWFiqAgZBcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFcR1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM", [file_google_protobuf_empty, file_google_protobuf_field_mask, file_store_note]);

/**
 * ListCategoriesRequest 列出分类请求
 *
 * @generated from message api.v1.ListCategoriesRequest
 */
export type ListCategoriesRequest = Message<"api.v1.ListCategoriesRequest"> & {
  /**
   * 是否包含隐藏的分类
   *
   * @generated from field: bool include_hidden = 1;
   */
  includeHidden: boolean;

  /**
   * 父分类ID（可选）
   *
   * @generated from field: int64 parent_id = 2;
   */
  parentId: bigint;
};

/**
 * Describes the message api.v1.ListCategoriesRequest.
 * Use `create(ListCategoriesRequestSchema)` to create a new message.
 */
export const ListCategoriesRequestSchema: GenMessage<ListCategoriesRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_category_service, 0);

/**
 * ListCategoriesResponse 列出分类响应
 *
 * @generated from message api.v1.ListCategoriesResponse
 */
export type ListCategoriesResponse = Message<"api.v1.ListCategoriesResponse"> & {
  /**
   * 分类列表
   *
   * @generated from field: repeated store.Category categories = 1;
   */
  categories: Category[];
};

/**
 * Describes the message api.v1.ListCategoriesResponse.
 * Use `create(ListCategoriesResponseSchema)` to create a new message.
 */
export const ListCategoriesResponseSchema: GenMessage<ListCategoriesResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_category_service, 1);

/**
 * GetCategoryRequest 获取分类请求
 *
 * @generated from message api.v1.GetCategoryRequest
 */
export type GetCategoryRequest = Message<"api.v1.GetCategoryRequest"> & {
  /**
   * 资源名称，格式：categories/{category}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.GetCategoryRequest.
 * Use `create(GetCategoryRequestSchema)` to create a new message.
 */
export const GetCategoryRequestSchema: GenMessage<GetCategoryRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_category_service, 2);

/**
 * CreateCategoryRequest 创建分类请求
 *
 * @generated from message api.v1.CreateCategoryRequest
 */
export type CreateCategoryRequest = Message<"api.v1.CreateCategoryRequest"> & {
  /**
   * 要创建的分类
   *
   * @generated from field: store.Category category = 1;
   */
  category?: Category;
};

/**
 * Describes the message api.v1.CreateCategoryRequest.
 * Use `create(CreateCategoryRequestSchema)` to create a new message.
 */
export const CreateCategoryRequestSchema: GenMessage<CreateCategoryRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_category_service, 3);

/**
 * UpdateCategoryRequest 更新分类请求
 *
 * @generated from message api.v1.UpdateCategoryRequest
 */
export type UpdateCategoryRequest = Message<"api.v1.UpdateCategoryRequest"> & {
  /**
   * 要更新的分类
   *
   * @generated from field: store.Category category = 1;
   */
  category?: Category;

  /**
   * 字段掩码，指定要更新的字段
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message api.v1.UpdateCategoryRequest.
 * Use `create(UpdateCategoryRequestSchema)` to create a new message.
 */
export const UpdateCategoryRequestSchema: GenMessage<UpdateCategoryRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_category_service, 4);

/**
 * DeleteCategoryRequest 删除分类请求
 *
 * @generated from message api.v1.DeleteCategoryRequest
 */
export type DeleteCategoryRequest = Message<"api.v1.DeleteCategoryRequest"> & {
  /**
   * 资源名称，格式：categories/{category}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.DeleteCategoryRequest.
 * Use `create(DeleteCategoryRequestSchema)` to create a new message.
 */
export const DeleteCategoryRequestSchema: GenMessage<DeleteCategoryRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_category_service, 5);

/**
 * GetCategoryBySlugRequest 根据slug获取分类请求
 *
 * @generated from message api.v1.GetCategoryBySlugRequest
 */
export type GetCategoryBySlugRequest = Message<"api.v1.GetCategoryBySlugRequest"> & {
  /**
   * slug标识符
   *
   * @generated from field: string slug = 1;
   */
  slug: string;
};

/**
 * Describes the message api.v1.GetCategoryBySlugRequest.
 * Use `create(GetCategoryBySlugRequestSchema)` to create a new message.
 */
export const GetCategoryBySlugRequestSchema: GenMessage<GetCategoryBySlugRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_category_service, 6);

/**
 * CategoryService 处理分类相关操作的服务
 *
 * @generated from service api.v1.CategoryService
 */
export const CategoryService: GenService<{
  /**
   * ListCategories 返回分类列表
   *
   * @generated from rpc api.v1.CategoryService.ListCategories
   */
  listCategories: {
    methodKind: "unary";
    input: typeof ListCategoriesRequestSchema;
    output: typeof ListCategoriesResponseSchema;
  },
  /**
   * GetCategory 根据ID返回单个分类
   *
   * @generated from rpc api.v1.CategoryService.GetCategory
   */
  getCategory: {
    methodKind: "unary";
    input: typeof GetCategoryRequestSchema;
    output: typeof CategorySchema;
  },
  /**
   * CreateCategory 创建新分类
   *
   * @generated from rpc api.v1.CategoryService.CreateCategory
   */
  createCategory: {
    methodKind: "unary";
    input: typeof CreateCategoryRequestSchema;
    output: typeof CategorySchema;
  },
  /**
   * UpdateCategory 更新现有分类
   *
   * @generated from rpc api.v1.CategoryService.UpdateCategory
   */
  updateCategory: {
    methodKind: "unary";
    input: typeof UpdateCategoryRequestSchema;
    output: typeof CategorySchema;
  },
  /**
   * DeleteCategory 删除分类
   *
   * @generated from rpc api.v1.CategoryService.DeleteCategory
   */
  deleteCategory: {
    methodKind: "unary";
    input: typeof DeleteCategoryRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * GetCategoryBySlug 根据slug返回分类
   *
   * @generated from rpc api.v1.CategoryService.GetCategoryBySlug
   */
  getCategoryBySlug: {
    methodKind: "unary";
    input: typeof GetCategoryBySlugRequestSchema;
    output: typeof CategorySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_category_service, 0);

