// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/comment_service.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Comment, CommentSchema } from "../../store/note_pb";
import { file_store_note } from "../../store/note_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/comment_service.proto.
 */
export const file_api_v1_comment_service: GenFile = /*@__PURE__*/
  fileDesc("ChxhcGkvdjEvY29tbWVudF9zZXJ2aWNlLnByb3RvEgZhcGkudjEiYwoTTGlzdENvbW1lbnRzUmVxdWVzdBIPCgdub3RlX2lkGAEgASgJEgwKBHBhZ2UYAiABKAUSEQoJcGFnZV9zaXplGAMgASgFEhoKEmluY2x1ZGVfdW5hcHByb3ZlZBgEIAEoCCJHChRMaXN0Q29tbWVudHNSZXNwb25zZRIgCghjb21tZW50cxgBIAMoCzIOLnN0b3JlLkNvbW1lbnQSDQoFdG90YWwYAiABKAUiNwoUQ3JlYXRlQ29tbWVudFJlcXVlc3QSHwoHY29tbWVudBgBIAEoCzIOLnN0b3JlLkNvbW1lbnQiaAoUVXBkYXRlQ29tbWVudFJlcXVlc3QSHwoHY29tbWVudBgBIAEoCzIOLnN0b3JlLkNvbW1lbnQSLwoLdXBkYXRlX21hc2sYAiABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIiQKFERlbGV0ZUNvbW1lbnRSZXF1ZXN0EgwKBG5hbWUYASABKAkiJQoVQXBwcm92ZUNvbW1lbnRSZXF1ZXN0EgwKBG5hbWUYASABKAky4QIKDkNvbW1lbnRTZXJ2aWNlEkkKDExpc3RDb21tZW50cxIbLmFwaS52MS5MaXN0Q29tbWVudHNSZXF1ZXN0GhwuYXBpLnYxLkxpc3RDb21tZW50c1Jlc3BvbnNlEj0KDUNyZWF0ZUNvbW1lbnQSHC5hcGkudjEuQ3JlYXRlQ29tbWVudFJlcXVlc3QaDi5zdG9yZS5Db21tZW50Ej0KDVVwZGF0ZUNvbW1lbnQSHC5hcGkudjEuVXBkYXRlQ29tbWVudFJlcXVlc3QaDi5zdG9yZS5Db21tZW50EkUKDURlbGV0ZUNvbW1lbnQSHC5hcGkudjEuRGVsZXRlQ29tbWVudFJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSPwoOQXBwcm92ZUNvbW1lbnQSHS5hcGkudjEuQXBwcm92ZUNvbW1lbnRSZXF1ZXN0Gg4uc3RvcmUuQ29tbWVudEKSAQoKY29tLmFwaS52MUITQ29tbWVudFNlcnZpY2VQcm90b1ABWjZnaXRodWIuY29tL3dkbXN5aGgvc2ltcGxlLW5vdGVzL3Byb3RvL2dlbi9hcGkvdjE7YXBpdjGiAgNBWFiqAgZBcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFcR1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM", [file_google_protobuf_empty, file_google_protobuf_field_mask, file_store_note]);

/**
 * ListCommentsRequest 列出评论请求
 *
 * @generated from message api.v1.ListCommentsRequest
 */
export type ListCommentsRequest = Message<"api.v1.ListCommentsRequest"> & {
  /**
   * 笔记ID
   *
   * @generated from field: string note_id = 1;
   */
  noteId: string;

  /**
   * 页码
   *
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   * 每页大小
   *
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;

  /**
   * 是否包含未审核的评论
   *
   * @generated from field: bool include_unapproved = 4;
   */
  includeUnapproved: boolean;
};

/**
 * Describes the message api.v1.ListCommentsRequest.
 * Use `create(ListCommentsRequestSchema)` to create a new message.
 */
export const ListCommentsRequestSchema: GenMessage<ListCommentsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_comment_service, 0);

/**
 * ListCommentsResponse 列出评论响应
 *
 * @generated from message api.v1.ListCommentsResponse
 */
export type ListCommentsResponse = Message<"api.v1.ListCommentsResponse"> & {
  /**
   * 评论列表
   *
   * @generated from field: repeated store.Comment comments = 1;
   */
  comments: Comment[];

  /**
   * 总数
   *
   * @generated from field: int32 total = 2;
   */
  total: number;
};

/**
 * Describes the message api.v1.ListCommentsResponse.
 * Use `create(ListCommentsResponseSchema)` to create a new message.
 */
export const ListCommentsResponseSchema: GenMessage<ListCommentsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_comment_service, 1);

/**
 * CreateCommentRequest 创建评论请求
 *
 * @generated from message api.v1.CreateCommentRequest
 */
export type CreateCommentRequest = Message<"api.v1.CreateCommentRequest"> & {
  /**
   * 要创建的评论
   *
   * @generated from field: store.Comment comment = 1;
   */
  comment?: Comment;
};

/**
 * Describes the message api.v1.CreateCommentRequest.
 * Use `create(CreateCommentRequestSchema)` to create a new message.
 */
export const CreateCommentRequestSchema: GenMessage<CreateCommentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_comment_service, 2);

/**
 * UpdateCommentRequest 更新评论请求
 *
 * @generated from message api.v1.UpdateCommentRequest
 */
export type UpdateCommentRequest = Message<"api.v1.UpdateCommentRequest"> & {
  /**
   * 要更新的评论
   *
   * @generated from field: store.Comment comment = 1;
   */
  comment?: Comment;

  /**
   * 字段掩码，指定要更新的字段
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message api.v1.UpdateCommentRequest.
 * Use `create(UpdateCommentRequestSchema)` to create a new message.
 */
export const UpdateCommentRequestSchema: GenMessage<UpdateCommentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_comment_service, 3);

/**
 * DeleteCommentRequest 删除评论请求
 *
 * @generated from message api.v1.DeleteCommentRequest
 */
export type DeleteCommentRequest = Message<"api.v1.DeleteCommentRequest"> & {
  /**
   * 资源名称，格式：comments/{comment}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.DeleteCommentRequest.
 * Use `create(DeleteCommentRequestSchema)` to create a new message.
 */
export const DeleteCommentRequestSchema: GenMessage<DeleteCommentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_comment_service, 4);

/**
 * ApproveCommentRequest 审核评论请求
 *
 * @generated from message api.v1.ApproveCommentRequest
 */
export type ApproveCommentRequest = Message<"api.v1.ApproveCommentRequest"> & {
  /**
   * 资源名称，格式：comments/{comment}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.ApproveCommentRequest.
 * Use `create(ApproveCommentRequestSchema)` to create a new message.
 */
export const ApproveCommentRequestSchema: GenMessage<ApproveCommentRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_comment_service, 5);

/**
 * CommentService 处理评论相关操作的服务
 *
 * @generated from service api.v1.CommentService
 */
export const CommentService: GenService<{
  /**
   * ListComments 返回笔记的评论列表
   *
   * @generated from rpc api.v1.CommentService.ListComments
   */
  listComments: {
    methodKind: "unary";
    input: typeof ListCommentsRequestSchema;
    output: typeof ListCommentsResponseSchema;
  },
  /**
   * CreateComment 创建新评论
   *
   * @generated from rpc api.v1.CommentService.CreateComment
   */
  createComment: {
    methodKind: "unary";
    input: typeof CreateCommentRequestSchema;
    output: typeof CommentSchema;
  },
  /**
   * UpdateComment 更新现有评论
   *
   * @generated from rpc api.v1.CommentService.UpdateComment
   */
  updateComment: {
    methodKind: "unary";
    input: typeof UpdateCommentRequestSchema;
    output: typeof CommentSchema;
  },
  /**
   * DeleteComment 删除评论
   *
   * @generated from rpc api.v1.CommentService.DeleteComment
   */
  deleteComment: {
    methodKind: "unary";
    input: typeof DeleteCommentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * ApproveComment 审核通过评论
   *
   * @generated from rpc api.v1.CommentService.ApproveComment
   */
  approveComment: {
    methodKind: "unary";
    input: typeof ApproveCommentRequestSchema;
    output: typeof CommentSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_comment_service, 0);

