// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/note_service.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Note, NoteSchema } from "../../store/note_pb";
import { file_store_note } from "../../store/note_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/note_service.proto.
 */
export const file_api_v1_note_service: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvdjEvbm90ZV9zZXJ2aWNlLnByb3RvEgZhcGkudjEijAEKEExpc3ROb3Rlc1JlcXVlc3QSDAoEcGFnZRgBIAEoBRIRCglwYWdlX3NpemUYAiABKAUSEwoLY2F0ZWdvcnlfaWQYAyABKAkSDgoGdGFnX2lkGAQgASgJEg4KBnNlYXJjaBgFIAEoCRIPCgdzb3J0X2J5GAYgASgJEhEKCXNvcnRfZGVzYxgHIAEoCCJ0ChFMaXN0Tm90ZXNSZXNwb25zZRIaCgVub3RlcxgBIAMoCzILLnN0b3JlLk5vdGUSDQoFdG90YWwYAiABKAUSDAoEcGFnZRgDIAEoBRIRCglwYWdlX3NpemUYBCABKAUSEwoLdG90YWxfcGFnZXMYBSABKAUiHgoOR2V0Tm90ZVJlcXVlc3QSDAoEbmFtZRgBIAEoCSIuChFDcmVhdGVOb3RlUmVxdWVzdBIZCgRub3RlGAEgASgLMgsuc3RvcmUuTm90ZSJfChFVcGRhdGVOb3RlUmVxdWVzdBIZCgRub3RlGAEgASgLMgsuc3RvcmUuTm90ZRIvCgt1cGRhdGVfbWFzaxgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2siIQoRRGVsZXRlTm90ZVJlcXVlc3QSDAoEbmFtZRgBIAEoCSIkChRHZXROb3RlQnlTbHVnUmVxdWVzdBIMCgRzbHVnGAEgASgJMugCCgtOb3RlU2VydmljZRJACglMaXN0Tm90ZXMSGC5hcGkudjEuTGlzdE5vdGVzUmVxdWVzdBoZLmFwaS52MS5MaXN0Tm90ZXNSZXNwb25zZRIuCgdHZXROb3RlEhYuYXBpLnYxLkdldE5vdGVSZXF1ZXN0Ggsuc3RvcmUuTm90ZRI0CgpDcmVhdGVOb3RlEhkuYXBpLnYxLkNyZWF0ZU5vdGVSZXF1ZXN0Ggsuc3RvcmUuTm90ZRI0CgpVcGRhdGVOb3RlEhkuYXBpLnYxLlVwZGF0ZU5vdGVSZXF1ZXN0Ggsuc3RvcmUuTm90ZRI/CgpEZWxldGVOb3RlEhkuYXBpLnYxLkRlbGV0ZU5vdGVSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EjoKDUdldE5vdGVCeVNsdWcSHC5hcGkudjEuR2V0Tm90ZUJ5U2x1Z1JlcXVlc3QaCy5zdG9yZS5Ob3RlQo8BCgpjb20uYXBpLnYxQhBOb3RlU2VydmljZVByb3RvUAFaNmdpdGh1Yi5jb20vd2Rtc3loaC9zaW1wbGUtbm90ZXMvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA0FYWKoCBkFwaS5WMcoCBkFwaVxWMeICEkFwaVxWMVxHUEJNZXRhZGF0YeoCB0FwaTo6VjFiBnByb3RvMw", [file_google_protobuf_empty, file_google_protobuf_field_mask, file_store_note]);

/**
 * ListNotesRequest 列出笔记请求
 *
 * @generated from message api.v1.ListNotesRequest
 */
export type ListNotesRequest = Message<"api.v1.ListNotesRequest"> & {
  /**
   * 页码
   *
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * 每页大小
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * 分类ID（可选）
   *
   * @generated from field: string category_id = 3;
   */
  categoryId: string;

  /**
   * 标签ID（可选）
   *
   * @generated from field: string tag_id = 4;
   */
  tagId: string;

  /**
   * 搜索关键词（可选）
   *
   * @generated from field: string search = 5;
   */
  search: string;

  /**
   * 排序字段（可选）
   *
   * @generated from field: string sort_by = 6;
   */
  sortBy: string;

  /**
   * 是否降序排序
   *
   * @generated from field: bool sort_desc = 7;
   */
  sortDesc: boolean;
};

/**
 * Describes the message api.v1.ListNotesRequest.
 * Use `create(ListNotesRequestSchema)` to create a new message.
 */
export const ListNotesRequestSchema: GenMessage<ListNotesRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_note_service, 0);

/**
 * ListNotesResponse 列出笔记响应
 *
 * @generated from message api.v1.ListNotesResponse
 */
export type ListNotesResponse = Message<"api.v1.ListNotesResponse"> & {
  /**
   * 笔记列表
   *
   * @generated from field: repeated store.Note notes = 1;
   */
  notes: Note[];

  /**
   * 总数
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * 当前页码
   *
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * 每页大小
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;

  /**
   * 总页数
   *
   * @generated from field: int32 total_pages = 5;
   */
  totalPages: number;
};

/**
 * Describes the message api.v1.ListNotesResponse.
 * Use `create(ListNotesResponseSchema)` to create a new message.
 */
export const ListNotesResponseSchema: GenMessage<ListNotesResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_note_service, 1);

/**
 * GetNoteRequest 获取笔记请求
 *
 * @generated from message api.v1.GetNoteRequest
 */
export type GetNoteRequest = Message<"api.v1.GetNoteRequest"> & {
  /**
   * 资源名称，格式：notes/{note}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.GetNoteRequest.
 * Use `create(GetNoteRequestSchema)` to create a new message.
 */
export const GetNoteRequestSchema: GenMessage<GetNoteRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_note_service, 2);

/**
 * CreateNoteRequest 创建笔记请求
 *
 * @generated from message api.v1.CreateNoteRequest
 */
export type CreateNoteRequest = Message<"api.v1.CreateNoteRequest"> & {
  /**
   * 要创建的笔记
   *
   * @generated from field: store.Note note = 1;
   */
  note?: Note;
};

/**
 * Describes the message api.v1.CreateNoteRequest.
 * Use `create(CreateNoteRequestSchema)` to create a new message.
 */
export const CreateNoteRequestSchema: GenMessage<CreateNoteRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_note_service, 3);

/**
 * UpdateNoteRequest 更新笔记请求
 *
 * @generated from message api.v1.UpdateNoteRequest
 */
export type UpdateNoteRequest = Message<"api.v1.UpdateNoteRequest"> & {
  /**
   * 要更新的笔记
   *
   * @generated from field: store.Note note = 1;
   */
  note?: Note;

  /**
   * 字段掩码，指定要更新的字段
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message api.v1.UpdateNoteRequest.
 * Use `create(UpdateNoteRequestSchema)` to create a new message.
 */
export const UpdateNoteRequestSchema: GenMessage<UpdateNoteRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_note_service, 4);

/**
 * DeleteNoteRequest 删除笔记请求
 *
 * @generated from message api.v1.DeleteNoteRequest
 */
export type DeleteNoteRequest = Message<"api.v1.DeleteNoteRequest"> & {
  /**
   * 资源名称，格式：notes/{note}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.DeleteNoteRequest.
 * Use `create(DeleteNoteRequestSchema)` to create a new message.
 */
export const DeleteNoteRequestSchema: GenMessage<DeleteNoteRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_note_service, 5);

/**
 * GetNoteBySlugRequest 根据slug获取笔记请求
 *
 * @generated from message api.v1.GetNoteBySlugRequest
 */
export type GetNoteBySlugRequest = Message<"api.v1.GetNoteBySlugRequest"> & {
  /**
   * slug标识符
   *
   * @generated from field: string slug = 1;
   */
  slug: string;
};

/**
 * Describes the message api.v1.GetNoteBySlugRequest.
 * Use `create(GetNoteBySlugRequestSchema)` to create a new message.
 */
export const GetNoteBySlugRequestSchema: GenMessage<GetNoteBySlugRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_note_service, 6);

/**
 * NoteService 处理笔记相关操作的服务
 *
 * @generated from service api.v1.NoteService
 */
export const NoteService: GenService<{
  /**
   * ListNotes 返回分页的笔记列表
   *
   * @generated from rpc api.v1.NoteService.ListNotes
   */
  listNotes: {
    methodKind: "unary";
    input: typeof ListNotesRequestSchema;
    output: typeof ListNotesResponseSchema;
  },
  /**
   * GetNote 根据ID返回单个笔记
   *
   * @generated from rpc api.v1.NoteService.GetNote
   */
  getNote: {
    methodKind: "unary";
    input: typeof GetNoteRequestSchema;
    output: typeof NoteSchema;
  },
  /**
   * CreateNote 创建新笔记
   *
   * @generated from rpc api.v1.NoteService.CreateNote
   */
  createNote: {
    methodKind: "unary";
    input: typeof CreateNoteRequestSchema;
    output: typeof NoteSchema;
  },
  /**
   * UpdateNote 更新现有笔记
   *
   * @generated from rpc api.v1.NoteService.UpdateNote
   */
  updateNote: {
    methodKind: "unary";
    input: typeof UpdateNoteRequestSchema;
    output: typeof NoteSchema;
  },
  /**
   * DeleteNote 删除笔记
   *
   * @generated from rpc api.v1.NoteService.DeleteNote
   */
  deleteNote: {
    methodKind: "unary";
    input: typeof DeleteNoteRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * GetNoteBySlug 根据slug返回笔记
   *
   * @generated from rpc api.v1.NoteService.GetNoteBySlug
   */
  getNoteBySlug: {
    methodKind: "unary";
    input: typeof GetNoteBySlugRequestSchema;
    output: typeof NoteSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_note_service, 0);

