// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/page_service.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Page, PageSchema } from "../../store/note_pb";
import { file_store_note } from "../../store/note_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/page_service.proto.
 */
export const file_api_v1_page_service: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvdjEvcGFnZV9zZXJ2aWNlLnByb3RvEgZhcGkudjEiLwoQTGlzdFBhZ2VzUmVxdWVzdBIbChNpbmNsdWRlX3VucHVibGlzaGVkGAEgASgIIi8KEUxpc3RQYWdlc1Jlc3BvbnNlEhoKBXBhZ2VzGAEgAygLMgsuc3RvcmUuUGFnZSIeCg5HZXRQYWdlUmVxdWVzdBIMCgRuYW1lGAEgASgJIi4KEUNyZWF0ZVBhZ2VSZXF1ZXN0EhkKBHBhZ2UYASABKAsyCy5zdG9yZS5QYWdlIl8KEVVwZGF0ZVBhZ2VSZXF1ZXN0EhkKBHBhZ2UYASABKAsyCy5zdG9yZS5QYWdlEi8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzayIhChFEZWxldGVQYWdlUmVxdWVzdBIMCgRuYW1lGAEgASgJIiQKFEdldFBhZ2VCeVNsdWdSZXF1ZXN0EgwKBHNsdWcYASABKAky6AIKC1BhZ2VTZXJ2aWNlEkAKCUxpc3RQYWdlcxIYLmFwaS52MS5MaXN0UGFnZXNSZXF1ZXN0GhkuYXBpLnYxLkxpc3RQYWdlc1Jlc3BvbnNlEi4KB0dldFBhZ2USFi5hcGkudjEuR2V0UGFnZVJlcXVlc3QaCy5zdG9yZS5QYWdlEjQKCkNyZWF0ZVBhZ2USGS5hcGkudjEuQ3JlYXRlUGFnZVJlcXVlc3QaCy5zdG9yZS5QYWdlEjQKClVwZGF0ZVBhZ2USGS5hcGkudjEuVXBkYXRlUGFnZVJlcXVlc3QaCy5zdG9yZS5QYWdlEj8KCkRlbGV0ZVBhZ2USGS5hcGkudjEuRGVsZXRlUGFnZVJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSOgoNR2V0UGFnZUJ5U2x1ZxIcLmFwaS52MS5HZXRQYWdlQnlTbHVnUmVxdWVzdBoLLnN0b3JlLlBhZ2VCjwEKCmNvbS5hcGkudjFCEFBhZ2VTZXJ2aWNlUHJvdG9QAVo2Z2l0aHViLmNvbS93ZG1zeWhoL3NpbXBsZS1ub3Rlcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDQVhYqgIGQXBpLlYxygIGQXBpXFYx4gISQXBpXFYxXEdQQk1ldGFkYXRh6gIHQXBpOjpWMWIGcHJvdG8z", [file_google_protobuf_empty, file_google_protobuf_field_mask, file_store_note]);

/**
 * ListPagesRequest 列出页面请求
 *
 * @generated from message api.v1.ListPagesRequest
 */
export type ListPagesRequest = Message<"api.v1.ListPagesRequest"> & {
  /**
   * 是否包含未发布的页面
   *
   * @generated from field: bool include_unpublished = 1;
   */
  includeUnpublished: boolean;
};

/**
 * Describes the message api.v1.ListPagesRequest.
 * Use `create(ListPagesRequestSchema)` to create a new message.
 */
export const ListPagesRequestSchema: GenMessage<ListPagesRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_page_service, 0);

/**
 * ListPagesResponse 列出页面响应
 *
 * @generated from message api.v1.ListPagesResponse
 */
export type ListPagesResponse = Message<"api.v1.ListPagesResponse"> & {
  /**
   * 页面列表
   *
   * @generated from field: repeated store.Page pages = 1;
   */
  pages: Page[];
};

/**
 * Describes the message api.v1.ListPagesResponse.
 * Use `create(ListPagesResponseSchema)` to create a new message.
 */
export const ListPagesResponseSchema: GenMessage<ListPagesResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_page_service, 1);

/**
 * GetPageRequest 获取页面请求
 *
 * @generated from message api.v1.GetPageRequest
 */
export type GetPageRequest = Message<"api.v1.GetPageRequest"> & {
  /**
   * 资源名称，格式：pages/{page}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.GetPageRequest.
 * Use `create(GetPageRequestSchema)` to create a new message.
 */
export const GetPageRequestSchema: GenMessage<GetPageRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_page_service, 2);

/**
 * CreatePageRequest 创建页面请求
 *
 * @generated from message api.v1.CreatePageRequest
 */
export type CreatePageRequest = Message<"api.v1.CreatePageRequest"> & {
  /**
   * 要创建的页面
   *
   * @generated from field: store.Page page = 1;
   */
  page?: Page;
};

/**
 * Describes the message api.v1.CreatePageRequest.
 * Use `create(CreatePageRequestSchema)` to create a new message.
 */
export const CreatePageRequestSchema: GenMessage<CreatePageRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_page_service, 3);

/**
 * UpdatePageRequest 更新页面请求
 *
 * @generated from message api.v1.UpdatePageRequest
 */
export type UpdatePageRequest = Message<"api.v1.UpdatePageRequest"> & {
  /**
   * 要更新的页面
   *
   * @generated from field: store.Page page = 1;
   */
  page?: Page;

  /**
   * 字段掩码，指定要更新的字段
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message api.v1.UpdatePageRequest.
 * Use `create(UpdatePageRequestSchema)` to create a new message.
 */
export const UpdatePageRequestSchema: GenMessage<UpdatePageRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_page_service, 4);

/**
 * DeletePageRequest 删除页面请求
 *
 * @generated from message api.v1.DeletePageRequest
 */
export type DeletePageRequest = Message<"api.v1.DeletePageRequest"> & {
  /**
   * 资源名称，格式：pages/{page}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.DeletePageRequest.
 * Use `create(DeletePageRequestSchema)` to create a new message.
 */
export const DeletePageRequestSchema: GenMessage<DeletePageRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_page_service, 5);

/**
 * GetPageBySlugRequest 根据slug获取页面请求
 *
 * @generated from message api.v1.GetPageBySlugRequest
 */
export type GetPageBySlugRequest = Message<"api.v1.GetPageBySlugRequest"> & {
  /**
   * slug标识符
   *
   * @generated from field: string slug = 1;
   */
  slug: string;
};

/**
 * Describes the message api.v1.GetPageBySlugRequest.
 * Use `create(GetPageBySlugRequestSchema)` to create a new message.
 */
export const GetPageBySlugRequestSchema: GenMessage<GetPageBySlugRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_page_service, 6);

/**
 * PageService 处理页面相关操作的服务
 *
 * @generated from service api.v1.PageService
 */
export const PageService: GenService<{
  /**
   * ListPages 返回页面列表
   *
   * @generated from rpc api.v1.PageService.ListPages
   */
  listPages: {
    methodKind: "unary";
    input: typeof ListPagesRequestSchema;
    output: typeof ListPagesResponseSchema;
  },
  /**
   * GetPage 根据ID返回单个页面
   *
   * @generated from rpc api.v1.PageService.GetPage
   */
  getPage: {
    methodKind: "unary";
    input: typeof GetPageRequestSchema;
    output: typeof PageSchema;
  },
  /**
   * CreatePage 创建新页面
   *
   * @generated from rpc api.v1.PageService.CreatePage
   */
  createPage: {
    methodKind: "unary";
    input: typeof CreatePageRequestSchema;
    output: typeof PageSchema;
  },
  /**
   * UpdatePage 更新现有页面
   *
   * @generated from rpc api.v1.PageService.UpdatePage
   */
  updatePage: {
    methodKind: "unary";
    input: typeof UpdatePageRequestSchema;
    output: typeof PageSchema;
  },
  /**
   * DeletePage 删除页面
   *
   * @generated from rpc api.v1.PageService.DeletePage
   */
  deletePage: {
    methodKind: "unary";
    input: typeof DeletePageRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * GetPageBySlug 根据slug返回页面
   *
   * @generated from rpc api.v1.PageService.GetPageBySlug
   */
  getPageBySlug: {
    methodKind: "unary";
    input: typeof GetPageBySlugRequestSchema;
    output: typeof PageSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_page_service, 0);

