// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/tag_service.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Tag, TagSchema } from "../../store/note_pb";
import { file_store_note } from "../../store/note_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/tag_service.proto.
 */
export const file_api_v1_tag_service: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvdjEvdGFnX3NlcnZpY2UucHJvdG8SBmFwaS52MSIwCg9MaXN0VGFnc1JlcXVlc3QSDQoFbGltaXQYASABKAUSDgoGb2Zmc2V0GAIgASgFIjsKEExpc3RUYWdzUmVzcG9uc2USGAoEdGFncxgBIAMoCzIKLnN0b3JlLlRhZxINCgV0b3RhbBgCIAEoBSIdCg1HZXRUYWdSZXF1ZXN0EgwKBG5hbWUYASABKAkiKwoQQ3JlYXRlVGFnUmVxdWVzdBIXCgN0YWcYASABKAsyCi5zdG9yZS5UYWciXAoQVXBkYXRlVGFnUmVxdWVzdBIXCgN0YWcYASABKAsyCi5zdG9yZS5UYWcSLwoLdXBkYXRlX21hc2sYAiABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIiAKEERlbGV0ZVRhZ1JlcXVlc3QSDAoEbmFtZRgBIAEoCSIjChNHZXRUYWdCeVNsdWdSZXF1ZXN0EgwKBHNsdWcYASABKAky1gIKClRhZ1NlcnZpY2USPQoITGlzdFRhZ3MSFy5hcGkudjEuTGlzdFRhZ3NSZXF1ZXN0GhguYXBpLnYxLkxpc3RUYWdzUmVzcG9uc2USKwoGR2V0VGFnEhUuYXBpLnYxLkdldFRhZ1JlcXVlc3QaCi5zdG9yZS5UYWcSMQoJQ3JlYXRlVGFnEhguYXBpLnYxLkNyZWF0ZVRhZ1JlcXVlc3QaCi5zdG9yZS5UYWcSMQoJVXBkYXRlVGFnEhguYXBpLnYxLlVwZGF0ZVRhZ1JlcXVlc3QaCi5zdG9yZS5UYWcSPQoJRGVsZXRlVGFnEhguYXBpLnYxLkRlbGV0ZVRhZ1JlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSNwoMR2V0VGFnQnlTbHVnEhsuYXBpLnYxLkdldFRhZ0J5U2x1Z1JlcXVlc3QaCi5zdG9yZS5UYWdCjgEKCmNvbS5hcGkudjFCD1RhZ1NlcnZpY2VQcm90b1ABWjZnaXRodWIuY29tL3dkbXN5aGgvc2ltcGxlLW5vdGVzL3Byb3RvL2dlbi9hcGkvdjE7YXBpdjGiAgNBWFiqAgZBcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFcR1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM", [file_google_protobuf_empty, file_google_protobuf_field_mask, file_store_note]);

/**
 * ListTagsRequest 列出标签请求
 *
 * @generated from message api.v1.ListTagsRequest
 */
export type ListTagsRequest = Message<"api.v1.ListTagsRequest"> & {
  /**
   * 限制返回数量（可选）
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * 偏移量（可选）
   *
   * @generated from field: int32 offset = 2;
   */
  offset: number;
};

/**
 * Describes the message api.v1.ListTagsRequest.
 * Use `create(ListTagsRequestSchema)` to create a new message.
 */
export const ListTagsRequestSchema: GenMessage<ListTagsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_tag_service, 0);

/**
 * ListTagsResponse 列出标签响应
 *
 * @generated from message api.v1.ListTagsResponse
 */
export type ListTagsResponse = Message<"api.v1.ListTagsResponse"> & {
  /**
   * 标签列表
   *
   * @generated from field: repeated store.Tag tags = 1;
   */
  tags: Tag[];

  /**
   * 总数
   *
   * @generated from field: int32 total = 2;
   */
  total: number;
};

/**
 * Describes the message api.v1.ListTagsResponse.
 * Use `create(ListTagsResponseSchema)` to create a new message.
 */
export const ListTagsResponseSchema: GenMessage<ListTagsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_tag_service, 1);

/**
 * GetTagRequest 获取标签请求
 *
 * @generated from message api.v1.GetTagRequest
 */
export type GetTagRequest = Message<"api.v1.GetTagRequest"> & {
  /**
   * 资源名称，格式：tags/{tag}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.GetTagRequest.
 * Use `create(GetTagRequestSchema)` to create a new message.
 */
export const GetTagRequestSchema: GenMessage<GetTagRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_tag_service, 2);

/**
 * CreateTagRequest 创建标签请求
 *
 * @generated from message api.v1.CreateTagRequest
 */
export type CreateTagRequest = Message<"api.v1.CreateTagRequest"> & {
  /**
   * 要创建的标签
   *
   * @generated from field: store.Tag tag = 1;
   */
  tag?: Tag;
};

/**
 * Describes the message api.v1.CreateTagRequest.
 * Use `create(CreateTagRequestSchema)` to create a new message.
 */
export const CreateTagRequestSchema: GenMessage<CreateTagRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_tag_service, 3);

/**
 * UpdateTagRequest 更新标签请求
 *
 * @generated from message api.v1.UpdateTagRequest
 */
export type UpdateTagRequest = Message<"api.v1.UpdateTagRequest"> & {
  /**
   * 要更新的标签
   *
   * @generated from field: store.Tag tag = 1;
   */
  tag?: Tag;

  /**
   * 字段掩码，指定要更新的字段
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message api.v1.UpdateTagRequest.
 * Use `create(UpdateTagRequestSchema)` to create a new message.
 */
export const UpdateTagRequestSchema: GenMessage<UpdateTagRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_tag_service, 4);

/**
 * DeleteTagRequest 删除标签请求
 *
 * @generated from message api.v1.DeleteTagRequest
 */
export type DeleteTagRequest = Message<"api.v1.DeleteTagRequest"> & {
  /**
   * 资源名称，格式：tags/{tag}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.DeleteTagRequest.
 * Use `create(DeleteTagRequestSchema)` to create a new message.
 */
export const DeleteTagRequestSchema: GenMessage<DeleteTagRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_tag_service, 5);

/**
 * GetTagBySlugRequest 根据slug获取标签请求
 *
 * @generated from message api.v1.GetTagBySlugRequest
 */
export type GetTagBySlugRequest = Message<"api.v1.GetTagBySlugRequest"> & {
  /**
   * slug标识符
   *
   * @generated from field: string slug = 1;
   */
  slug: string;
};

/**
 * Describes the message api.v1.GetTagBySlugRequest.
 * Use `create(GetTagBySlugRequestSchema)` to create a new message.
 */
export const GetTagBySlugRequestSchema: GenMessage<GetTagBySlugRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_tag_service, 6);

/**
 * TagService 处理标签相关操作的服务
 *
 * @generated from service api.v1.TagService
 */
export const TagService: GenService<{
  /**
   * ListTags 返回标签列表
   *
   * @generated from rpc api.v1.TagService.ListTags
   */
  listTags: {
    methodKind: "unary";
    input: typeof ListTagsRequestSchema;
    output: typeof ListTagsResponseSchema;
  },
  /**
   * GetTag 根据ID返回单个标签
   *
   * @generated from rpc api.v1.TagService.GetTag
   */
  getTag: {
    methodKind: "unary";
    input: typeof GetTagRequestSchema;
    output: typeof TagSchema;
  },
  /**
   * CreateTag 创建新标签
   *
   * @generated from rpc api.v1.TagService.CreateTag
   */
  createTag: {
    methodKind: "unary";
    input: typeof CreateTagRequestSchema;
    output: typeof TagSchema;
  },
  /**
   * UpdateTag 更新现有标签
   *
   * @generated from rpc api.v1.TagService.UpdateTag
   */
  updateTag: {
    methodKind: "unary";
    input: typeof UpdateTagRequestSchema;
    output: typeof TagSchema;
  },
  /**
   * DeleteTag 删除标签
   *
   * @generated from rpc api.v1.TagService.DeleteTag
   */
  deleteTag: {
    methodKind: "unary";
    input: typeof DeleteTagRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * GetTagBySlug 根据slug返回标签
   *
   * @generated from rpc api.v1.TagService.GetTagBySlug
   */
  getTagBySlug: {
    methodKind: "unary";
    input: typeof GetTagBySlugRequestSchema;
    output: typeof TagSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_tag_service, 0);

