// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/user_service.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { User, UserSchema } from "../../store/note_pb";
import { file_store_note } from "../../store/note_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/user_service.proto.
 */
export const file_api_v1_user_service: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvdjEvdXNlcl9zZXJ2aWNlLnByb3RvEgZhcGkudjEiQgoTUmVnaXN0ZXJVc2VyUmVxdWVzdBIZCgR1c2VyGAEgASgLMgsuc3RvcmUuVXNlchIQCghwYXNzd29yZBgCIAEoCSI2ChBMb2dpblVzZXJSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIj0KEUxvZ2luVXNlclJlc3BvbnNlEhkKBHVzZXIYASABKAsyCy5zdG9yZS5Vc2VyEg0KBXRva2VuGAIgASgJIh4KDkdldFVzZXJSZXF1ZXN0EgwKBG5hbWUYASABKAkiFwoVR2V0Q3VycmVudFVzZXJSZXF1ZXN0Il8KEVVwZGF0ZVVzZXJSZXF1ZXN0EhkKBHVzZXIYASABKAsyCy5zdG9yZS5Vc2VyEi8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzayIhChFEZWxldGVVc2VyUmVxdWVzdBIMCgRuYW1lGAEgASgJIkMKEExpc3RVc2Vyc1JlcXVlc3QSDAoEcGFnZRgBIAEoBRIRCglwYWdlX3NpemUYAiABKAUSDgoGc2VhcmNoGAMgASgJIl8KEUxpc3RVc2Vyc1Jlc3BvbnNlEhoKBXVzZXJzGAEgAygLMgsuc3RvcmUuVXNlchINCgV0b3RhbBgCIAEoBRIMCgRwYWdlGAMgASgFEhEKCXBhZ2Vfc2l6ZRgEIAEoBTKwAwoLVXNlclNlcnZpY2USOAoMUmVnaXN0ZXJVc2VyEhsuYXBpLnYxLlJlZ2lzdGVyVXNlclJlcXVlc3QaCy5zdG9yZS5Vc2VyEkAKCUxvZ2luVXNlchIYLmFwaS52MS5Mb2dpblVzZXJSZXF1ZXN0GhkuYXBpLnYxLkxvZ2luVXNlclJlc3BvbnNlEi4KB0dldFVzZXISFi5hcGkudjEuR2V0VXNlclJlcXVlc3QaCy5zdG9yZS5Vc2VyEjwKDkdldEN1cnJlbnRVc2VyEh0uYXBpLnYxLkdldEN1cnJlbnRVc2VyUmVxdWVzdBoLLnN0b3JlLlVzZXISNAoKVXBkYXRlVXNlchIZLmFwaS52MS5VcGRhdGVVc2VyUmVxdWVzdBoLLnN0b3JlLlVzZXISPwoKRGVsZXRlVXNlchIZLmFwaS52MS5EZWxldGVVc2VyUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRJACglMaXN0VXNlcnMSGC5hcGkudjEuTGlzdFVzZXJzUmVxdWVzdBoZLmFwaS52MS5MaXN0VXNlcnNSZXNwb25zZUKPAQoKY29tLmFwaS52MUIQVXNlclNlcnZpY2VQcm90b1ABWjZnaXRodWIuY29tL3dkbXN5aGgvc2ltcGxlLW5vdGVzL3Byb3RvL2dlbi9hcGkvdjE7YXBpdjGiAgNBWFiqAgZBcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFcR1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM", [file_google_protobuf_empty, file_google_protobuf_field_mask, file_store_note]);

/**
 * RegisterUserRequest 注册用户请求
 *
 * @generated from message api.v1.RegisterUserRequest
 */
export type RegisterUserRequest = Message<"api.v1.RegisterUserRequest"> & {
  /**
   * 要注册的用户信息
   *
   * @generated from field: store.User user = 1;
   */
  user?: User;

  /**
   * 密码（单独发送以确保安全）
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message api.v1.RegisterUserRequest.
 * Use `create(RegisterUserRequestSchema)` to create a new message.
 */
export const RegisterUserRequestSchema: GenMessage<RegisterUserRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 0);

/**
 * LoginUserRequest 登录用户请求
 *
 * @generated from message api.v1.LoginUserRequest
 */
export type LoginUserRequest = Message<"api.v1.LoginUserRequest"> & {
  /**
   * 用户名
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * 密码
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message api.v1.LoginUserRequest.
 * Use `create(LoginUserRequestSchema)` to create a new message.
 */
export const LoginUserRequestSchema: GenMessage<LoginUserRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 1);

/**
 * LoginUserResponse 登录用户响应
 *
 * @generated from message api.v1.LoginUserResponse
 */
export type LoginUserResponse = Message<"api.v1.LoginUserResponse"> & {
  /**
   * 用户信息
   *
   * @generated from field: store.User user = 1;
   */
  user?: User;

  /**
   * 认证令牌
   *
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message api.v1.LoginUserResponse.
 * Use `create(LoginUserResponseSchema)` to create a new message.
 */
export const LoginUserResponseSchema: GenMessage<LoginUserResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 2);

/**
 * GetUserRequest 获取用户请求
 *
 * @generated from message api.v1.GetUserRequest
 */
export type GetUserRequest = Message<"api.v1.GetUserRequest"> & {
  /**
   * 资源名称，格式：users/{user}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 3);

/**
 * GetCurrentUserRequest 获取当前用户请求
 *
 * 无需参数，用户通过认证令牌识别
 *
 * @generated from message api.v1.GetCurrentUserRequest
 */
export type GetCurrentUserRequest = Message<"api.v1.GetCurrentUserRequest"> & {
};

/**
 * Describes the message api.v1.GetCurrentUserRequest.
 * Use `create(GetCurrentUserRequestSchema)` to create a new message.
 */
export const GetCurrentUserRequestSchema: GenMessage<GetCurrentUserRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 4);

/**
 * UpdateUserRequest 更新用户请求
 *
 * @generated from message api.v1.UpdateUserRequest
 */
export type UpdateUserRequest = Message<"api.v1.UpdateUserRequest"> & {
  /**
   * 要更新的用户信息
   *
   * @generated from field: store.User user = 1;
   */
  user?: User;

  /**
   * 字段掩码，指定要更新的字段
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message api.v1.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema: GenMessage<UpdateUserRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 5);

/**
 * DeleteUserRequest 删除用户请求
 *
 * @generated from message api.v1.DeleteUserRequest
 */
export type DeleteUserRequest = Message<"api.v1.DeleteUserRequest"> & {
  /**
   * 资源名称，格式：users/{user}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api.v1.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export const DeleteUserRequestSchema: GenMessage<DeleteUserRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 6);

/**
 * ListUsersRequest 列出用户请求
 *
 * @generated from message api.v1.ListUsersRequest
 */
export type ListUsersRequest = Message<"api.v1.ListUsersRequest"> & {
  /**
   * 页码
   *
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * 每页大小
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * 搜索关键词（可选）
   *
   * @generated from field: string search = 3;
   */
  search: string;
};

/**
 * Describes the message api.v1.ListUsersRequest.
 * Use `create(ListUsersRequestSchema)` to create a new message.
 */
export const ListUsersRequestSchema: GenMessage<ListUsersRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 7);

/**
 * ListUsersResponse 列出用户响应
 *
 * @generated from message api.v1.ListUsersResponse
 */
export type ListUsersResponse = Message<"api.v1.ListUsersResponse"> & {
  /**
   * 用户列表
   *
   * @generated from field: repeated store.User users = 1;
   */
  users: User[];

  /**
   * 总数
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * 当前页码
   *
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * 每页大小
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;
};

/**
 * Describes the message api.v1.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export const ListUsersResponseSchema: GenMessage<ListUsersResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_user_service, 8);

/**
 * UserService 处理用户相关操作的服务
 *
 * @generated from service api.v1.UserService
 */
export const UserService: GenService<{
  /**
   * RegisterUser 注册新用户
   *
   * @generated from rpc api.v1.UserService.RegisterUser
   */
  registerUser: {
    methodKind: "unary";
    input: typeof RegisterUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * LoginUser 认证用户并返回认证令牌
   *
   * @generated from rpc api.v1.UserService.LoginUser
   */
  loginUser: {
    methodKind: "unary";
    input: typeof LoginUserRequestSchema;
    output: typeof LoginUserResponseSchema;
  },
  /**
   * GetUser 根据ID返回单个用户
   *
   * @generated from rpc api.v1.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * GetCurrentUser 返回当前已认证的用户
   *
   * @generated from rpc api.v1.UserService.GetCurrentUser
   */
  getCurrentUser: {
    methodKind: "unary";
    input: typeof GetCurrentUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * UpdateUser 更新现有用户
   *
   * @generated from rpc api.v1.UserService.UpdateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * DeleteUser 删除用户
   *
   * @generated from rpc api.v1.UserService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * ListUsers 返回分页的用户列表
   *
   * @generated from rpc api.v1.UserService.ListUsers
   */
  listUsers: {
    methodKind: "unary";
    input: typeof ListUsersRequestSchema;
    output: typeof ListUsersResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_user_service, 0);

